apiVersion: v1
kind: Service
metadata:
  name: app-version # service name (can be my-app-svc)
  namespace: my-app
spec:
  type: LoadBalancer
  selector:
    app: app-version # must match template.metadata.labels.<label>
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000 