apiVersion: v1
kind: Secret
metadata:
  name: ecr-private-secret
  namespace: my-app
stringData:
  AWS_ACCESS_KEY_ID: "${aws_access_key_id}"
  AWS_SECRET_ACCESS_KEY: "${aws_secret_access_key}"
  AWS_ACCOUNT_ID: "${aws_account_id}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-private-cm
  namespace: my-app
data:
  AWS_REGION: "${aws_region}"
  DOCKER_SECRET_NAME: regcred
---